---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3c810c56c70061fc90cf94bd6730b476cd38d1ff
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/07/2019
ms.locfileid: "72015143"
---
# <a name="c28163"></a>C28163
Warnung C28163: Die Funktion sollte nie innerhalb eines try/with-Blocks aufgerufen werden.

 Diese Warnung wird gemeldet, wenn eine Funktion einen Typ hat, der niemals in einen `try/except`-Block eingeschlossen werden sollte, der in einem `try/except`-Block gefunden wird. Das Code Analysetool hat mindestens einen Pfad gefunden, in dem die Funktion mit dem Namen innerhalb eines `try/except`-Blocks war.