---
title: C6312
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: be42518fd34867ff149849b70a470506c4e9cba9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/16/2019
ms.locfileid: "72449705"
---
# <a name="c6312"></a>C6312
Warnung C6312: Mögliche Endlosschleife: Verwendung der EXCEPTION_CONTINUE_EXECUTION-Konstanten im Ausnahmefilterausdruck einer try-except-Anweisung.

 Diese Warnung gibt die Verwendung des Konstanten `EXCEPTION_CONTINUE_EXECUTION` (oder einer anderen Konstante, die zu-1 ausgewertet wird) im Filter Ausdruck eines strukturierten Ausnahme Handlers an. Die Verwendung des konstanten Werts `EXCEPTION_CONTINUE_EXECUTION` kann zu einer Endlosschleife führen. Wenn z. b. eine Ausnahme von der Hardware ausgelöst wurde, wird die Anweisung, die die Ausnahme verursacht hat, neu gestartet. Wenn die Adresse, die die Ausnahme verursacht hat, immer noch schlecht ist, wird eine andere Ausnahme auftreten und auf die gleiche Weise behandelt. Dies verursacht eine Endlosschleife.

 Ein expliziter aufrufungs `RaiseException` führt nicht direkt zu einer Endlosschleife, sondern wird die Ausführung des Codes im geschützten Block fortsetzen. Dies kann unerwartet sein und zu einer Endlosschleife führen, wenn `RaiseException` verwendet wurde, um das Dereferenzieren eines ungültigen Zeigers zu vermeiden.

 In der Regel sollten `EXCEPTION_CONTINUE_EXECUTION` nur von einer im Filter Ausdruck aufgerufenen Funktion zurückgegeben werden, die die Möglichkeit hat, entweder den Zeiger zu korrigieren, der die Ausnahme verursacht hat, oder den zugrunde liegenden Arbeitsspeicher.

## <a name="example"></a>Beispiel
 Der folgende Code generiert diese Warnung:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```
